### PR TITLE
iOS fix

### PR DESCRIPTION
**Pull request by buu700**
Possible fix for #139. I had an issue with building so I wasn't able to test this at all, but this is my next best attempt after finding out in the comments there that https://github.com/jedisct1/libsodium/pull/691 wasn't enough.

### CODE REVIEW

**Comment by jedisct1** [comment]
The latest Emscripten still has the `__errno` issue :(

**Comment by ryancwalsh** [comment]
@buu700 Thanks for your work, and I'd love to try out your fix. **Is there a way for me to use a dependency other than https://www.npmjs.com/package/libsodium-wrappers so that I'm pulling straight from your new code instead of that 8-month old code?** I could update the [Codesandbox fiddle](https://github.com/jedisct1/libsodium.js/issues/139#issuecomment-415198773) and see whether it works on iOS 11.2. Thanks.

**Comment by ryancwalsh** [comment]
@buu700 I think I figured out how to [pull from](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies) that commit.

I edited my `package.json` to have this: `"libsodium-wrappers": "https://github.com/jedisct1/libsodium.js.git#96c1c974b13fe9641a91d1ff4832ec838eb84c2a"`

I think [Codesandbox](https://codesandbox.io/s/885py74lm9?autoresize=1&expanddevtools=1&hidenavigation=1) doesn't support pulling dependencies from Github.

But in my own local project, I'm pretty sure* I was able to successfully pull your commit in that way, and it works on desktop but unfortunately still does not work on iOS 11.2. 

*If there is something I can look for within my `node_modules` folder to double-check that your fix is there and being used, let me know. Thanks.

**Comment by ryancwalsh** [comment]
https://www.npmjs.com/package/libsodium-wrappers 0.7.3 works on iPhone 6S with old iOS 10.3.3. (I just tested my partner's phone.)

**Comment by buu700** [comment]
Not a problem! My new code hasn't been compiled yet because I ran an issue with the build script, so instead of spending more time fighting with it I just submitted what I had for an initial review.

@jedisct1, if you're able to rebuild successfully, would you be able to upload it here for @ryancwalsh to test on his iOS 11.2 device? (I figure we should confirm that it actually does what was intended before committing or publishing it.)

**Comment by buu700** [comment]
I don't see any reason why it shouldn't work soon. I have no idea what the issue is to be honest (beyond that the emscripten runtime's wasm logic doesn't like something about iOS 11.2), but the idea of this fix is that if the wasm blows up during initialization for any reason it automatically falls back to asm.js — i.e. the bugs in dependencies don't really matter as long as the asm.js is still able to startup.

As far as libsodium not building for me, that's probably just an issue on my end since it's been a while since I've had to build it; I assume building still works for @jedisct1.

> P.S. I clicked into your profile and saw https://www.cyph.com/ — very cool :-)

Thanks!

**Pull request merged**
