### PR TITLE
Added a to_string helper for consistency

### PR DESCRIPTION
**Pull request by buu700**

### CODE REVIEW

**Comment by jedisct1** [comment]
`from_string()` returns a vector of bytes which represent the text encoded as a UTF-8 string.

In order to reverse this operation, `new TextDecoder("utf-8").decode(str)` would do the right thing when `TextDecoder` is present. But I don't think that your code would return the correct result if the environment charset is not UTF-8.

**Comment by jedisct1** [comment]
Actually it won't return the expected result is the text is not Latin-1.

**Comment by buu700** [comment]
Ah, sorry about that. (I actually only tried adding this to begin with because I hadn't realised I could pass in an extra argument with "text" as the output encoding format to the functions I was using – so this may or may not be a useful change to begin with.)

**Comment by buu700** [comment]
Not sure if it's something you want in libsodium.js, but I did end up needing this in my code, so I just fixed the to_string function.

(No problem if not; I'm just keeping the function in my code for now.)

Also, sorry, ignore PR #16.

**Comment by jedisct1** [comment]
Great!

However, there is an inconsistency between `TextDecoder()` and your alternative implementation.

When an invalid string is given, TextDecoder replaces nonexistent code points with � (code 65533).
Whereas `decodeURIComponent()` returns an `URIError` exception.

Both are acceptable, but we have to pick one. If we return an exception, `URIError` might not be the best one.

**Comment by buu700** [comment]
Ah, good catch. How does it look now? I just set TextDecoder to fail on invalid input and copied its error type + message for the polyfill.

**Comment by jedisct1** [comment]
Looks great!

Merged.

Thank you for this nice and useful addition, Ryan!

**Comment by buu700** [comment]
No problem; thanks for accepting it!

**Pull request merged**
