### PR TITLE
Return entire module as promise

### PR DESCRIPTION
**Pull request by buu700**
As discussed in #105.

### CODE REVIEW

**Comment by jedisct1** [comment]
Awesome!

**Comment by buu700** [comment]
Oh, sorry, just noticed I forgot to remove line 565 (thought I'd done that before committing).

**Comment by jedisct1** [comment]
No problem. Removed :)

**Comment by jedisct1** [comment]
Aie. It doesn't seem to work, at least without wasm.

```js
> require('libsodium-wrappers')
```
```js
{ add: [Function],
  base64_variants:
   { ORIGINAL: 1,
     ORIGINAL_NO_PADDING: 3,
     URLSAFE: 5,
     URLSAFE_NO_PADDING: 7 },
  compare: [Function],
  from_base64: [Function],
  from_hex: [Function],
  from_string: [Function: a],
  increment: [Function],
  is_zero: [Function] }
```

**Comment by jedisct1** [comment]
And with wasm, the promise is rejected

```
ReferenceError: libsodiumModule is not defined
```

**Comment by jedisct1** [comment]
Don't bother if this looks hard to fix, we can stick to the previous system with the promise returned along with other properties.

**Comment by jedisct1** [comment]
00e8ed0d792acc23b8bd0b000261aa1d99269865 probably fixes the second thing :)

**Comment by jedisct1** [comment]
Now without wasm we get all the symbols. But directly, instead of the promise.

**Comment by buu700** [comment]
Oops, sorry about the `libsodiumModule` oversight. Not exactly sure why it would return everything directly in the non-wasm case, but #109 might fix that.

**Pull request merged**
