### PR TITLE
First pull request. Improvements, added license, updated readme and automated doc building

### PR DESCRIPTION
**Pull request by BatikhSouri**
Hey,

Here are the things I've done in my fork:
* As you suggested: combining `encode_utf8` + `encode_latin1` into a `uint8array_to_String` method. The corresponding `decode` have been combined into `string_to_Uint8Array`
* The `uint` macro now allows `0`
* Deallocates the buffers from the heap once a function reaches its end
* Re-imported the test page and vectors into the `test` folder
* Added a copy of `emscripten.sh` that includes `pre.js.inc` on compilation. This file is copied into the submodule before launching the build
* Added `make rewrap` to allow rebuilding the wrapper without relaunching emscripten
* Added the low-level scrypt function as part of the symbols exported by default (in the local copy of `emscripten.sh`
* Added an automated doc builder that runs as part of the wrapper build script. Writes an `API.md` file in the root folder after writing the `libsodium-wrap.js`
* Updated the README.md
* Choose the ISC license. Does it suits you?

__Note:__ I [tried](https://github.com/LockateMe/libsodium.js/blob/hex/js-build/wrap-template.js#L35) to change the hex encoding/decoding to use the helper methods from the library, but I didn't get it to work for now.

### CODE REVIEW

**Comment by jedisct1** [comment]
Awesome!

Merged.

**Comment by jedisct1** [comment]
Shouldn't we leave the call to `./autogen.sh`? A fresh clone on the repository is not going to work without it.

**Comment by BatikhSouri** [comment]
It already does it in the `libsodium/configure` target, right? If you're are talking about line 14 that is commented out, we can remove it. I've added it before writing the `rewrap` target.

**Comment by jedisct1** [comment]
Right, I forgot about that dependency :)

Looks like emscripten doesn't properly emit the initial randombytes structure, but instead we probably don't need code that relies on `/dev/urandom` anyway.

https://github.com/jedisct1/libsodium.js/commit/6a97bbc7f5bb3e3703f5ea96202824558f7ee7c1 is an attempt at it. Works fine with the io.js REPL.

**Comment by BatikhSouri** [comment]
Alright cool :) I get you did here. Though Chrome doesn't like it yet. First, since the template starts with entering in strict mode, that wouldn't allow "nested functions". Provided that we removed the "use strict" directive (which entered the code from @saleware's original snippet about building a js wrapper, from [here](https://github.com/jedisct1/libsodium/issues/178#issuecomment-48799706)), an error is thrown stating that there we ran out of reserved functions pointers.

**Pull request merged**
