### PR TITLE
Added crypto_auth_hmacsha512256 wrappers, new wrapper tests, and made sumo wrapper tests easier to run

### PR DESCRIPTION
**Pull request by bschick**
Wanted to compare crypto_auth_hmacsha512256 and keyed crypto_generichash from javascript. So did the following:

- Added wrappers for.crypto_auth_hmacsha512256*
- Added wrapper tests for crypto_auth_hmacsha512256 and crypto_generichash
- Made is easier to test normal vs sumo packages (without errors)

### CODE REVIEW

**Comment by jedisct1** [comment]
Thank you!

But for unrelated changes, distinct PRs would have been better!

Thanks!

**Comment by jedisct1** [comment]
But wait...

Now, in the regular packages, there's a `testsumo` target that doesn't work, and in sumo packages, the `test` target doesn't test everything.

Looks like a regression.

**Comment by bschick** [comment]
Hmmm, not sure what you are seeing (or what is different on my system). When I do the following it all works as expected:

```
> git clone https://github.com/bschick/libsodium.js.git
> cd libsodium.js/
> make 
> npm run test
> npm run testsumo
```
It all works as expected and tests pass. 

Before my changes, `make test` failed because the crypto_pwhash is only part of the sumo package. The new `testsumo` target has crypto_pwhash and crypto_auth_hmacsha512256 tests because those are in sumo.

Also, I assume you know that in npm land some scripts like "test", "start", "build" are special and don't require the "run" command. So you can do `npm test` but not `npm testsumo`.

**Comment by jedisct1** [comment]
I was referring to the actual packages, that will be distributed on npm.

**Comment by jedisct1** [comment]
>  Is the 'script' section even needed in those?

Yes. 

That's actually my release script:

```sh
#! /bin/sh

for f in \
  package-libsodium.json \
  package-libsodium-sumo.json \
  package-libsodium-wrappers-sumo.json \
  package-libsodium-wrappers.json \
; do
  rm -f package.json
  cp "$f" package.json
  npm publish || yarn publish
done
rm -f package.json
cp package-libsodium-wrappers.json package.json
```

Maybe there's an easier way to publish these different packages. I don't know.

**Comment by bschick** [comment]
Got it, apologies for missing those. I made this update, but it looks like you are already make these changes upstream :)
https://github.com/jedisct1/libsodium.js/compare/master...bschick:libsodium.js:master

I see you also removed `testsumo` from the base pacakge.json. I'd propose leaving that in so you don't have to run the release and overwrite package.json to test both versions of wrappers. It did work as expected, but you have to run it with `npm run testsumo` since testsumo is not one of the special npm targets like "build", "start", "test" that allow you to drop "run".

**Comment by bschick** [comment]
Oh, but then the final `cp package-libsodium-wrappers.json package.json` will leave a diff. Could save and replace the original.

**Comment by jedisct1** [comment]
`package.json` is not really meant to be used. It's just there for convenience in order to install the dependencies.

But it can be. copy of `package-libsodium-wrappers-sumo.json` instead of `package-libsodium-wrappers.json` if you prefer.

**Comment by bschick** [comment]
Sure. Certainly cleaner as you did it, although a bit less obvious. Thanks for taking the pull request and the library overall.

**Pull request merged**
