### PR TITLE
Ristretto255 wrappers

### PR DESCRIPTION
**Pull request by zaenk**
Submitting `crypto*_ristretto255*` wrappers for review.

I'm not familiar with wasm and wrapping, so give it a good look, please.

### CODE REVIEW

**Comment by zaenk** [comment]
Also: @ffflorian I also made typings, you can find it in this gist: https://gist.github.com/zaenk/9fbb5d988531aacaefa0a9fbfddd4ffd

**Comment by zaenk** [comment]
I did not commit the latest built js files. Should I commit them before this PR is accepted?

**Comment by jedisct1** [comment]
Thanks a lot for these!

I don't have a computer now but I'll take a look shortly.

Note that if you only need these functions, [wasm-crypto](https://github.com/jedisct1/wasm-crypto) may be an alternative to libsodium.js.

**Comment by jedisct1** [comment]
No need to rebuild the JS file, I'll do it :)

**Comment by ffflorian** [comment]
Will this be part of libsodium-wrappers or just libsodium-wrappers-sumo?

**Comment by zaenk** [comment]
Only libsodium-wrappers-sumo

**Comment by jedisct1** [comment]
Looking good! Thank you!

**Pull request merged**
