### PR TITLE
Replaced Exception with Error because Exception is not defined

### PR DESCRIPTION
**Pull request by bennyn**

### CODE REVIEW

**Comment by jedisct1** [comment]
Good catch, thanks!

**Comment by bennyn** [comment]
When it was a good catch then why did you close my pull request? :disappointed:

**Comment by lipis** [comment]
not cool.. :/ maybe it was an accident

**Comment by jedisct1** [comment]
This was merged, but as a commit that only include the onliner change: https://github.com/jedisct1/libsodium.js/commit/ab0832def2bb28c57b7982aa17cab4496b6ae09a

The precompiled files were added in a distinct commit, in order to use the latest Emscripten version, and include the zopfli-compressed files as well.

**Comment by lipis** [comment]
it's not fair for the contributor though that way.. if anything it's better to suggest changes to the current PR.. otherwise what's the point?

**Comment by bennyn** [comment]
Damn it. That was my chance to get a [libsodium.js contributor](https://github.com/jedisct1/libsodium.js/graphs/contributors). :see_no_evil:

**Pull request closed without merging**
